# Generated by Django 3.1.5 on 2022-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sqaure_image',
            field=models.ImageField(default='', upload_to='pics/gallery'),
            preserve_default=False,
        ),
    ]
