# Generated by Django 3.1.5 on 2022-03-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_website_deatil'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_Deatil',
            new_name='WebsiteDetail',
        ),
    ]
