# Generated by Django 3.1.5 on 2022-03-22 06:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_websitedetail_linked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='about_second_detail',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='about_second_image',
            field=models.ImageField(default='', upload_to='pics/about'),
            preserve_default=False,
        ),
    ]
