# Generated by Django 3.1.5 on 2022-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20220322_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='about_page_heading',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
