# Generated by Django 3.1.5 on 2022-03-22 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_websitedetail_about_page_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_square_thumbnail', models.ImageField(upload_to='pics/project')),
                ('project_image', models.ImageField(upload_to='picc/project')),
                ('project_detail', ckeditor.fields.RichTextField()),
                ('client', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('started_date', models.CharField(max_length=150)),
                ('finished_data', models.CharField(max_length=100)),
            ],
        ),
    ]
