# Generated by Django 3.1.5 on 2022-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_websitedetail_about_company_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='bottom_contact_detail',
            field=models.TextField(default='I loved painting and drawing for many reasons. One of them was that all it really required was me, a pencil and a pad. It was something I was passionate about, and still am I loved painting.'),
            preserve_default=False,
        ),
    ]
