# Generated by Django 3.1.5 on 2022-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_websitedetail_bottom_contact_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='recent_project_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='recent_project_heading',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
