# Generated by Django 3.1.5 on 2022-03-22 18:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20220322_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='homepage_about_us',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
