# Generated by Django 3.1.5 on 2022-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_websitedetail_homepage_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='homepage_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='homepage_heading',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
