# Generated by Django 3.1.5 on 2022-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20220323_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='phone_number',
            field=models.CharField(default='+91 (992) 078 7450', max_length=20),
            preserve_default=False,
        ),
    ]
