# Generated by Django 3.1.5 on 2022-03-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_websitedetail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='contact_email',
            field=models.CharField(default='Panvel Paradise, Akurli', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='short_address',
            field=models.CharField(default='Panvel Paradise, Akurli', max_length=150),
            preserve_default=False,
        ),
    ]
