# Generated by Django 3.1.5 on 2022-03-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='sqaure_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='pics/project'),
        ),
    ]
