# Generated by Django 3.1.5 on 2022-03-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20220326_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_square_thumbnail',
        ),
    ]
