# Generated by Django 3.1.5 on 2022-03-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_remove_project_project_square_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitedetail',
            old_name='recent_project_description',
            new_name='gallery_description',
        ),
        migrations.RenameField(
            model_name='websitedetail',
            old_name='recent_project_heading',
            new_name='gallery_heading',
        ),
    ]
