# Generated by Django 3.1.5 on 2022-04-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20220330_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
