# Generated by Django 3.1.5 on 2022-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
