# Generated by Django 3.1.5 on 2022-04-30 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_testimonial_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_heading', models.CharField(max_length=500)),
                ('project_image', models.ImageField(upload_to='pics/project')),
                ('image_mode', models.CharField(choices=[('12', 'Landscape'), ('4', 'Portrait')], max_length=2)),
                ('project_detail', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='On_Going_Project_Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='On_Going_Project_Heading',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
