# Generated by Django 3.1.5 on 2022-05-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_homepagescroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagescroll',
            old_name='Title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='homepagescroll',
            name='Description',
        ),
    ]
