# Generated by Django 3.1.5 on 2022-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_auto_20220503_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image',
            new_name='project_image_1',
        ),
        migrations.RenameField(
            model_name='recentproject',
            old_name='project_image',
            new_name='project_image_1',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='recentproject',
            name='project_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='recentproject',
            name='project_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='recentproject',
            name='project_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
        migrations.AddField(
            model_name='recentproject',
            name='project_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='pics/project'),
        ),
    ]
